TRUNCATE TABLE t_demande_statut RESTART IDENTITY CASCADE;

TRUNCATE TABLE t_demande RESTART IDENTITY CASCADE;

TRUNCATE TABLE t_client RESTART IDENTITY CASCADE;

TRUNCATE TABLE t_type_devis RESTART IDENTITY CASCADE;

TRUNCATE TABLE t_statut RESTART IDENTITY CASCADE;

TRUNCATE TABLE t_detail_devis RESTART IDENTITY CASCADE;

TRUNCATE TABLE t_devis RESTART IDENTITY CASCADE;

TRUNCATE TABLE t_statut_devis RESTART IDENTITY CASCADE;